name: flutter_stock

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.22.0" 

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.2.1
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  supabase_flutter: ^2.9.1
  flutter_slidable: ^4.0.1
  flutter_svg: ^2.0.10+1
  intl: ^0.20.2
  google_maps_flutter: ^2.9.0
  collection: ^1.18.0
  uuid: ^4.4.0
  geolocator: ^14.0.2
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^19.4.1
  path_provider: ^2.1.5
  path: ^1.9.1
  drift: ^2.28.1
  timezone: ^0.10.1
  url_launcher: ^6.3.2
  

dev_dependencies:
  freezed: ^3.2.0
  json_serializable: ^6.11.0
  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  drift_dev: ^2.28.1

flutter:
  uses-material-design: true
  assets:
    - .env
