name: flutter_stock
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.22.0" 

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.2.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  supabase_flutter: ^2.6.0
  flutter_slidable: ^4.0.1
  flutter_svg: ^2.0.10+1
  intl: ^0.20.2
  google_maps_flutter: ^2.9.0
  collection: ^1.18.0
  uuid: ^4.4.0
  geolocator: any
  flutter_dotenv: any

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^3.2.0
  json_serializable: ^6.9.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true