name: flutter_stock

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3 # New line
  go_router: ^16.2.1
  flutter_riverpod: ^3.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  supabase_flutter: ^2.9.1
  flutter_slidable: ^4.0.1
  intl: ^0.20.2
  google_maps_flutter: ^2.9.0
  collection: ^1.18.0
  uuid: ^4.4.0
  geolocator: ^14.0.2
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3
  google_mlkit_text_recognition: ^0.11.0
  image_picker: ^1.1.2
  google_maps_cluster_manager_2: ^3.2.0
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.1.0
  url_launcher: ^6.3.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  freezed: ^2.5.0
  json_serializable: ^6.8.0
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  integration_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#1A237E"
  image: assets/splash/splash_logo.png
  android_12:
    image: assets/splash/splash_logo.png
    color: "#1A237E"
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/empty_state.png
